// GENERATED by teardown_857_prescott.py ù do not hand-edit.
// Removes ONLY the seed data for one project id.
const PROJECT_ID = '6a7921aaccdc4ed5f63ec8e4';
const EXECUTE    = true;

const FORBIDDEN_BINS    = ['3048298', '3255362'];
const FORBIDDEN_MARKERS = ['8 walworth', 'walworth st', '588 thomas', 'thomas s boyland', 'boyland'];
const ALLOWED_NAME      = '857 prescott pl';

function oid(v) { try { return new ObjectId(v); } catch (e) { return v; } }

const proj = db.projects.findOne({ _id: oid(PROJECT_ID) })
          || db.projects.findOne({ _id: PROJECT_ID });
if (!proj) { print("REFUSING: no project with id " + PROJECT_ID); quit(1); }

const hay = [proj.name, proj.address, proj.location, proj.bin, proj.bin_number]
  .map(v => String(v || "").toLowerCase()).join(" | ");

for (const bin of FORBIDDEN_BINS) {
  if (hay.indexOf(bin) !== -1) {
    print("REFUSING: project " + PROJECT_ID + " matches production BIN " + bin);
    quit(1);
  }
}
for (const m of FORBIDDEN_MARKERS) {
  if (hay.indexOf(m) !== -1) {
    print("REFUSING: project " + PROJECT_ID + " matches production site '" + m + "'");
    quit(1);
  }
}
if (String(proj.name || "").trim().toLowerCase() !== ALLOWED_NAME) {
  print("REFUSING: project name is '" + proj.name + "', expected '" + ALLOWED_NAME + "'");
  print("This script only ever deletes the seeded test project.");
  quit(1);
}
print("Target confirmed: '" + proj.name + "'  (" + PROJECT_ID + ")");
print(EXECUTE ? "MODE: EXECUTE" : "MODE: DRY-RUN (nothing will be deleted)");
print("");

const TARGETS = [['checkins', 'project_id'], ['logbooks', 'project_id'], ['nfc_tags', 'project_id'], ['worker_project_trades', 'project_id'], ['daily_logs', 'project_id'], ['signature_events', 'project_id']];
let total = 0;
for (const [coll, field] of TARGETS) {
  const q = {}; q[field] = PROJECT_ID;
  const n = db[coll].countDocuments(q);
  total += n;
  if (n === 0) { print("  " + coll + ": 0"); continue; }
  if (EXECUTE) {
    const r = db[coll].deleteMany(q);
    print("  " + coll + ": deleted " + r.deletedCount);
  } else {
    print("  " + coll + ": would delete " + n);
  }
}

// The project row last, so a failure part-way leaves it findable.
const pq = { _id: proj._id };
if (EXECUTE) {
  db.projects.deleteOne(pq);
  print("  projects: deleted 1");
} else {
  print("  projects: would delete 1");
}
print("");
print("total non-project docs: " + total);
print("");
print("NOT DELETED, ON PURPOSE: the `workers` collection.");
print("Workers are GLOBAL, not per-project ù a worker seeded here may also");
print("have checked in on a live site, and deleting by phone would take a real");
print("person's record with it. The seed phones are 347-555-01xx; remove them");
print("by hand only if you have confirmed they exist nowhere else.");
