"""Remove everything seed_857_prescott.py created. Nothing else.

DRY RUN BY DEFAULT.

    python teardown_857_prescott.py --project-id <ID>
    python teardown_857_prescott.py --project-id <ID> --execute

SCOPED TO ONE PROJECT ID, AND FENCED AGAINST THE LIVE SITES.

Every delete is filtered on project_id == the id you pass. Before anything
runs, the script fetches that project and REFUSES if it looks like production:

  * name or address matching 8 Walworth / 588 Thomas S Boyland
  * BIN 3048298 or 3255362
  * a name that is not exactly "857 Prescott Pl"

The last check is the real fence — an explicit allowlist of one name beats a
denylist, because a denylist only stops the sites someone thought to list. The
BIN and address checks stay anyway as a second, independent tripwire.

This is a MongoDB script (mongosh): the API has no bulk-delete path, and the
per-record DELETE endpoints soft-delete rather than remove, which would leave
this throwaway data in every query that does not filter is_deleted. Teardown of
seed data should leave nothing behind, so it goes direct — which is safe here
precisely because it is deletion, not creation: nothing downstream reads a
shape this script produces.

    mongosh "$ATLAS_URI" --file teardown_857_prescott.js --eval 'var PROJECT_ID="..."'

The .js companion is generated by this script so the two cannot drift:

    python teardown_857_prescott.py --project-id <ID> --emit-js > teardown.js
"""

from __future__ import annotations

import argparse
import sys

# Hardcoded. These two are the live NYC jobsites; nothing here may touch them.
FORBIDDEN_BINS = ["3048298", "3255362"]
FORBIDDEN_MARKERS = [
    "8 walworth", "walworth st",
    "588 thomas", "thomas s boyland", "boyland",
]
ALLOWED_PROJECT_NAME = "857 prescott pl"

# Collections the seed writes into, and the field each is keyed on.
# workers is NOT here on purpose — see the note printed at the end.
TARGETS = [
    ("checkins", "project_id"),
    ("logbooks", "project_id"),
    ("nfc_tags", "project_id"),
    ("worker_project_trades", "project_id"),
    ("daily_logs", "project_id"),
    ("signature_events", "project_id"),
]

JS_TEMPLATE = r"""// GENERATED by teardown_857_prescott.py — do not hand-edit.
// Removes ONLY the seed data for one project id.
const PROJECT_ID = %(pid)r;
const EXECUTE    = %(execute)s;

const FORBIDDEN_BINS    = %(bins)s;
const FORBIDDEN_MARKERS = %(markers)s;
const ALLOWED_NAME      = %(allowed)r;

function oid(v) { try { return new ObjectId(v); } catch (e) { return v; } }

const proj = db.projects.findOne({ _id: oid(PROJECT_ID) })
          || db.projects.findOne({ _id: PROJECT_ID });
if (!proj) { print("REFUSING: no project with id " + PROJECT_ID); quit(1); }

const hay = [proj.name, proj.address, proj.location, proj.bin, proj.bin_number]
  .map(v => String(v || "").toLowerCase()).join(" | ");

for (const bin of FORBIDDEN_BINS) {
  if (hay.indexOf(bin) !== -1) {
    print("REFUSING: project " + PROJECT_ID + " matches production BIN " + bin);
    quit(1);
  }
}
for (const m of FORBIDDEN_MARKERS) {
  if (hay.indexOf(m) !== -1) {
    print("REFUSING: project " + PROJECT_ID + " matches production site '" + m + "'");
    quit(1);
  }
}
if (String(proj.name || "").trim().toLowerCase() !== ALLOWED_NAME) {
  print("REFUSING: project name is '" + proj.name + "', expected '" + ALLOWED_NAME + "'");
  print("This script only ever deletes the seeded test project.");
  quit(1);
}
print("Target confirmed: '" + proj.name + "'  (" + PROJECT_ID + ")");
print(EXECUTE ? "MODE: EXECUTE" : "MODE: DRY-RUN (nothing will be deleted)");
print("");

const TARGETS = %(targets)s;
let total = 0;
for (const [coll, field] of TARGETS) {
  const q = {}; q[field] = PROJECT_ID;
  const n = db[coll].countDocuments(q);
  total += n;
  if (n === 0) { print("  " + coll + ": 0"); continue; }
  if (EXECUTE) {
    const r = db[coll].deleteMany(q);
    print("  " + coll + ": deleted " + r.deletedCount);
  } else {
    print("  " + coll + ": would delete " + n);
  }
}

// The project row last, so a failure part-way leaves it findable.
const pq = { _id: proj._id };
if (EXECUTE) {
  db.projects.deleteOne(pq);
  print("  projects: deleted 1");
} else {
  print("  projects: would delete 1");
}
print("");
print("total non-project docs: " + total);
print("");
print("NOT DELETED, ON PURPOSE: the `workers` collection.");
print("Workers are GLOBAL, not per-project — a worker seeded here may also");
print("have checked in on a live site, and deleting by phone would take a real");
print("person's record with it. The seed phones are 347-555-01xx; remove them");
print("by hand only if you have confirmed they exist nowhere else.");
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--project-id", required=True)
    ap.add_argument("--execute", action="store_true")
    ap.add_argument("--emit-js", action="store_true",
                    help="print the mongosh script to stdout and exit")
    a = ap.parse_args()

    js = JS_TEMPLATE % {
        "pid": a.project_id,
        "execute": "true" if a.execute else "false",
        "bins": FORBIDDEN_BINS,
        "markers": FORBIDDEN_MARKERS,
        "allowed": ALLOWED_PROJECT_NAME,
        "targets": [list(t) for t in TARGETS],
    }
    if a.emit_js:
        sys.stdout.write(js)
        return

    print("This script GENERATES the mongosh teardown; it does not connect to")
    print("any database itself.\n")
    print(f"  project id : {a.project_id}")
    print(f"  mode       : {'EXECUTE' if a.execute else 'DRY-RUN'}")
    print(f"  fenced off : BINs {', '.join(FORBIDDEN_BINS)}")
    print(f"               {', '.join(FORBIDDEN_MARKERS)}")
    print(f"  will only run against a project named exactly '{ALLOWED_PROJECT_NAME}'\n")
    print("Write it out and run it:\n")
    print(f"  python teardown_857_prescott.py --project-id {a.project_id}"
          f"{' --execute' if a.execute else ''} --emit-js > teardown.js")
    print('  mongosh "$ATLAS_URI" --file teardown.js\n')


if __name__ == "__main__":
    main()
