"""Phase B2 — tests for backend/scripts/audit_production.py.

Coverage:

  ReadOnlyDatabase guard
    • collection.insert_one() raises RuntimeError, not silently no-ops.
    • Every banned method on _BANNED_COLLECTION_METHODS raises.
    • Read methods (find, count_documents, aggregate, find_one,
      index_information) pass through unmolested.

  Python preset detection port
    • detect_active_preset returns the right key for each of the
      three preset shapes generated by the Python helpers.
    • detect_active_preset returns 'custom' for arbitrary other
      shapes + the empty record case.
    • Python ALL_KINDS / CRITICAL_EMAIL_KINDS / STANDARD_DIGEST_KINDS
      constants match the JS source verbatim (parsed via regex from
      frontend/src/utils/notificationPresets.js).
    • Round-trip: feed prefs constructed from JS-derived constants
      into detect_active_preset; verify it returns the matching
      preset key.

  Concern severity validation
    • Concern() with valid severity constructs cleanly.
    • Concern() with invalid severity raises ValueError.

  Section 7 canary behavior
    • CanaryFailed exception class exists and inherits Exception.
    • run_audit returns 1 + emits a BLOCKER markdown line when the
      canary trips.

  Static-source pins
    • Script defines run_audit + _main_entry + ReadOnlyDatabase.
    • Script reads MONGO_URL + DB_NAME from environment.
    • Script registers all 10 audit sections (excluding Section 11
      Atlas-manual which is not a runner).
"""

from __future__ import annotations

import asyncio
import os
import re
import sys
import unittest
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, patch

os.environ.setdefault("MONGO_URL", "mongodb://localhost:27017")
os.environ.setdefault("DB_NAME", "smoke_test")

_HERE = Path(__file__).resolve().parent
_BACKEND = _HERE.parent
_REPO = _BACKEND.parent
_FRONTEND = _REPO / "frontend"
sys.path.insert(0, str(_BACKEND))


def _run(coro):
    return asyncio.run(coro)


# ── ReadOnlyDatabase guard ────────────────────────────────────────


class TestReadOnlyGuard(unittest.TestCase):

    def _wrapped_collection(self):
        from scripts.audit_production import ReadOnlyCollection
        # Build a mock that pretends to be a Motor collection. The
        # name attribute is what the wrapper surfaces in error
        # messages.
        real = MagicMock()
        real.name = "test_coll"
        # Attach reasonable attributes for read methods.
        real.find = MagicMock()
        real.count_documents = AsyncMock(return_value=42)
        real.aggregate = MagicMock()
        real.find_one = AsyncMock(return_value=None)
        real.index_information = AsyncMock(return_value={})
        return ReadOnlyCollection(real), real

    def test_insert_one_raises(self):
        wrapped, _ = self._wrapped_collection()
        with self.assertRaises(RuntimeError) as cm:
            _ = wrapped.insert_one  # access alone triggers the guard
        self.assertIn("read-only", str(cm.exception).lower())
        self.assertIn("insert_one", str(cm.exception))

    def test_every_banned_method_raises(self):
        from scripts.audit_production import _BANNED_COLLECTION_METHODS
        wrapped, _ = self._wrapped_collection()
        for method in _BANNED_COLLECTION_METHODS:
            with self.assertRaises(RuntimeError, msg=method):
                _ = getattr(wrapped, method)

    def test_read_methods_pass_through(self):
        wrapped, real = self._wrapped_collection()
        # find / count_documents / aggregate / find_one / index_information
        # all pass through to the underlying collection.
        self.assertIs(wrapped.find, real.find)
        self.assertIs(wrapped.count_documents, real.count_documents)
        self.assertIs(wrapped.aggregate, real.aggregate)
        self.assertIs(wrapped.find_one, real.find_one)
        self.assertIs(wrapped.index_information, real.index_information)

    def test_collection_name_property_passes_through(self):
        wrapped, _ = self._wrapped_collection()
        self.assertEqual(wrapped.name, "test_coll")


class TestReadOnlyDatabaseSubscript(unittest.TestCase):

    def test_subscript_returns_wrapped_collection(self):
        from scripts.audit_production import (
            ReadOnlyDatabase, ReadOnlyCollection,
        )
        # Mock the underlying database. db['name'] returns a Motor
        # collection mock; we wrap it.
        raw_db = MagicMock()
        coll_mock = MagicMock()
        coll_mock.name = "users"
        raw_db.__getitem__.return_value = coll_mock
        ro = ReadOnlyDatabase(raw_db)
        result = ro["users"]
        self.assertIsInstance(result, ReadOnlyCollection)
        # Banned methods should still raise on the subscript-accessed
        # collection.
        with self.assertRaises(RuntimeError):
            _ = result.delete_many


# ── Python preset detection port ──────────────────────────────────


class TestPythonPresetDetectionMatchesPresetGenerators(unittest.TestCase):
    """Round-trip the Python-built preset shapes through Python
    detection. If detect_active_preset's normalization logic drifts
    from the build_preset_* logic, this test fires."""

    def test_critical_only_round_trip(self):
        from scripts.audit_production import (
            build_preset_overrides,
            build_preset_channel_routes,
            detect_active_preset,
        )
        prefs = {
            "signal_kind_overrides": build_preset_overrides("critical_only"),
            "channel_routes_default": build_preset_channel_routes("critical_only"),
        }
        self.assertEqual(detect_active_preset(prefs), "critical_only")

    def test_standard_round_trip(self):
        from scripts.audit_production import (
            build_preset_overrides,
            build_preset_channel_routes,
            detect_active_preset,
        )
        prefs = {
            "signal_kind_overrides": build_preset_overrides("standard"),
            "channel_routes_default": build_preset_channel_routes("standard"),
        }
        self.assertEqual(detect_active_preset(prefs), "standard")

    def test_everything_round_trip(self):
        from scripts.audit_production import (
            build_preset_overrides,
            build_preset_channel_routes,
            detect_active_preset,
        )
        prefs = {
            "signal_kind_overrides": build_preset_overrides("everything"),
            "channel_routes_default": build_preset_channel_routes("everything"),
        }
        self.assertEqual(detect_active_preset(prefs), "everything")

    def test_custom_returned_for_unknown_shape(self):
        from scripts.audit_production import detect_active_preset
        prefs = {
            "signal_kind_overrides": {
                "violation_dob": {"channels": ["email"], "delivery": "immediate"},
                # Missing the other 25 kinds → doesn't match any preset.
            },
            "channel_routes_default": {"critical": ["email"], "warning": [], "info": []},
        }
        self.assertEqual(detect_active_preset(prefs), "custom")

    def test_empty_returns_custom(self):
        from scripts.audit_production import detect_active_preset
        self.assertEqual(detect_active_preset(None), "custom")
        self.assertEqual(detect_active_preset({}), "custom")


class TestPythonPresetDetectionMatchesJS(unittest.TestCase):
    """Loads frontend/src/utils/notificationPresets.js source, extracts
    the constants via regex (same approach as
    test_notification_presets_shape.py), verifies the Python
    constants are byte-equal."""

    PRESETS_FILE = (
        _FRONTEND / "src" / "utils" / "notificationPresets.js"
    )

    def _extract_kind_list(self, source: str, marker: str):
        pattern = (
            rf"export const {re.escape(marker)} = \[(.*?)\];"
        )
        match = re.search(pattern, source, re.DOTALL)
        if not match:
            return []
        body = match.group(1)
        body = re.sub(r"//[^\n]*", "", body)
        return re.findall(r"'([^']+)'", body)

    def test_python_all_kinds_matches_js(self):
        from scripts.audit_production import ALL_KINDS
        text = self.PRESETS_FILE.read_text(encoding="utf-8")
        js_kinds = self._extract_kind_list(text, "ALL_KINDS")
        self.assertEqual(
            sorted(ALL_KINDS),
            sorted(js_kinds),
            "Python ALL_KINDS must match JS notificationPresets.js",
        )

    def test_python_critical_email_kinds_matches_js(self):
        from scripts.audit_production import CRITICAL_EMAIL_KINDS
        text = self.PRESETS_FILE.read_text(encoding="utf-8")
        js_kinds = self._extract_kind_list(text, "CRITICAL_EMAIL_KINDS")
        self.assertEqual(
            sorted(CRITICAL_EMAIL_KINDS),
            sorted(js_kinds),
            "Python CRITICAL_EMAIL_KINDS must match JS",
        )

    def test_python_standard_digest_kinds_matches_js(self):
        from scripts.audit_production import STANDARD_DIGEST_KINDS
        text = self.PRESETS_FILE.read_text(encoding="utf-8")
        js_kinds = self._extract_kind_list(text, "STANDARD_DIGEST_KINDS")
        self.assertEqual(
            sorted(STANDARD_DIGEST_KINDS),
            sorted(js_kinds),
            "Python STANDARD_DIGEST_KINDS must match JS",
        )

    def test_python_preset_routes_match_js_literals(self):
        """The JS source has three literal channel_routes_default
        objects, one per preset. Verify Python's
        build_preset_channel_routes returns the same shapes."""
        from scripts.audit_production import build_preset_channel_routes
        text = self.PRESETS_FILE.read_text(encoding="utf-8")
        # Critical only: { critical: ['email'], warning: [], info: [] }
        self.assertIn(
            "{ critical: ['email'], warning: [], info: [] }",
            text,
        )
        self.assertEqual(
            build_preset_channel_routes("critical_only"),
            {"critical": ["email"], "warning": [], "info": []},
        )
        # Standard: { critical: ['email'], warning: ['email'], info: [] }
        self.assertIn(
            "{ critical: ['email'], warning: ['email'], info: [] }",
            text,
        )
        self.assertEqual(
            build_preset_channel_routes("standard"),
            {"critical": ["email"], "warning": ["email"], "info": []},
        )
        # Everything: { critical: ['email'], warning: ['email'], info: ['email'] }
        self.assertIn(
            "{ critical: ['email'], warning: ['email'], info: ['email'] }",
            text,
        )
        self.assertEqual(
            build_preset_channel_routes("everything"),
            {"critical": ["email"], "warning": ["email"], "info": ["email"]},
        )


class TestNormalizationOutputFormat(unittest.TestCase):
    """The Python normalizers must produce JS-equivalent JSON
    strings (no spaces between separators) so the hash inputs match
    byte-for-byte."""

    def test_normalize_override_entry_compact(self):
        from scripts.audit_production import _normalize_override_entry
        out = _normalize_override_entry(
            {"channels": ["email"], "severity_threshold": "any", "delivery": "immediate"}
        )
        # No spaces — matches JS JSON.stringify output.
        self.assertEqual(
            out,
            '{"channels":["email"],"severity_threshold":"any","delivery":"immediate"}',
        )

    def test_normalize_override_entry_handles_missing_fields(self):
        from scripts.audit_production import _normalize_override_entry
        out = _normalize_override_entry({})
        self.assertEqual(
            out,
            '{"channels":[],"severity_threshold":"any","delivery":"feed_only"}',
        )

    def test_normalize_routes_compact(self):
        from scripts.audit_production import _normalize_routes
        out = _normalize_routes(
            {"critical": ["email"], "warning": [], "info": ["in_app"]}
        )
        self.assertEqual(
            out,
            '{"critical":["email"],"warning":[],"info":["in_app"]}',
        )


# ── Concern model ─────────────────────────────────────────────────


class TestConcern(unittest.TestCase):

    def test_valid_severity_constructs(self):
        from scripts.audit_production import Concern, SEVERITY_BLOCKER
        c = Concern(
            severity=SEVERITY_BLOCKER,
            section="1. Projects",
            summary="Test",
        )
        self.assertEqual(c.severity, "BLOCKER")

    def test_invalid_severity_raises(self):
        from scripts.audit_production import Concern
        with self.assertRaises(ValueError):
            Concern(
                severity="MEDIUM",  # not in VALID_SEVERITIES
                section="x", summary="y",
            )

    def test_to_markdown_row_includes_severity_badge(self):
        from scripts.audit_production import Concern, SEVERITY_WARNING
        c = Concern(
            severity=SEVERITY_WARNING,
            section="x", summary="something",
            detail="some detail", fix_path="fix it",
        )
        md = c.to_markdown_row()
        self.assertIn("**[WARNING]**", md)
        self.assertIn("something", md)
        self.assertIn("some detail", md)
        self.assertIn("fix it", md)


# ── Section 7 canary ──────────────────────────────────────────────


class TestSection7Canary(unittest.TestCase):

    def test_canary_failed_is_an_exception(self):
        from scripts.audit_production import CanaryFailed
        self.assertTrue(issubclass(CanaryFailed, Exception))

    def test_canary_raises_when_credentials_present(self):
        """When companies.count_documents on the
        filing_reps.credentials filter returns > 0, the canary
        section raises CanaryFailed (not warns)."""
        from scripts.audit_production import (
            CanaryFailed, section_filing_reps_canary, ReadOnlyDatabase,
        )
        raw_db = MagicMock()
        raw_db.companies = MagicMock()
        # Pretend 3 docs still carry the legacy field.
        raw_db.companies.count_documents = AsyncMock(return_value=3)
        # Need to also stub aggregate + find for the no-creds branch
        # (won't be reached but the wrapper still inspects
        # __getattr__).
        ro = ReadOnlyDatabase(raw_db)
        # ReadOnlyDatabase wraps via isinstance(AsyncIOMotorCollection)
        # which our MagicMock isn't — so __getattr__ returns the raw
        # mock. Patch the wrapper's instance check to treat any
        # MagicMock as a collection for this test.
        from scripts import audit_production as mod
        with patch.object(mod, "AsyncIOMotorCollection", MagicMock):
            with self.assertRaises(CanaryFailed):
                _run(section_filing_reps_canary(ro))

    def test_canary_clean_when_zero_records(self):
        from scripts.audit_production import (
            section_filing_reps_canary, ReadOnlyDatabase,
        )

        class _AsyncCursor:
            def __init__(self, items):
                self._items = items
            def __aiter__(self):
                async def _gen():
                    for it in self._items:
                        yield it
                return _gen()
            def sort(self, *a, **kw): return self
            def limit(self, n): return self

        raw_db = MagicMock()
        raw_db.companies = MagicMock()
        raw_db.companies.count_documents = AsyncMock(return_value=0)
        raw_db.companies.aggregate = MagicMock(return_value=_AsyncCursor([
            {"_id": "co_a", "name": "Acme", "rep_count": 2},
        ]))
        raw_db.companies.find = MagicMock(return_value=_AsyncCursor([
            {"filing_reps": [{"email": "rep1@example.com"}]},
        ]))
        raw_db.users = MagicMock()
        raw_db.users.find = MagicMock(return_value=_AsyncCursor([]))

        ro = ReadOnlyDatabase(raw_db)
        from scripts import audit_production as mod
        with patch.object(mod, "AsyncIOMotorCollection", MagicMock):
            md, concerns = _run(section_filing_reps_canary(ro))
        self.assertIn("CANARY CLEAN", md)
        # rep1@example.com is a filing_rep without a user account →
        # that's an INFO concern.
        info_concerns = [c for c in concerns if c.severity == "INFO"]
        self.assertEqual(len(info_concerns), 1)


# ── run_audit canary failure path ────────────────────────────────


class TestRunAuditCanaryAborts(unittest.TestCase):

    def test_run_audit_returns_1_on_canary_fail(self):
        """When the canary trips during run_audit, the function
        returns exit code 1."""
        from scripts import audit_production as mod
        # Build a mock client + db. We patch the section runner
        # list to call the canary first (which it already does),
        # and the canary's count_documents returns 5.
        raw_db = MagicMock()
        raw_db.companies = MagicMock()
        raw_db.companies.count_documents = AsyncMock(return_value=5)

        class FakeClient:
            def __getitem__(self, name):
                return raw_db

        with patch.object(mod, "AsyncIOMotorClient", lambda *a, **kw: FakeClient()), \
             patch.object(mod, "AsyncIOMotorCollection", MagicMock):
            # Replace SECTION_RUNNERS with just the canary so the
            # other sections don't try to query the mock for shapes
            # we haven't stubbed.
            with patch.object(
                mod, "SECTION_RUNNERS",
                [("filing_reps canary", mod.section_filing_reps_canary)],
            ):
                rc = _run(mod.run_audit("mongodb://x", "smoke_test"))
        self.assertEqual(rc, 1)


# ── Static-source pins ────────────────────────────────────────────


SCRIPT_PATH = _BACKEND / "scripts" / "audit_production.py"


class TestScriptStaticPins(unittest.TestCase):

    def test_script_present(self):
        self.assertTrue(SCRIPT_PATH.exists())

    def test_script_reads_env_vars(self):
        text = SCRIPT_PATH.read_text(encoding="utf-8")
        self.assertIn('os.environ.get("MONGO_URL")', text)
        self.assertIn('os.environ.get("DB_NAME")', text)

    def test_script_defines_read_only_classes(self):
        text = SCRIPT_PATH.read_text(encoding="utf-8")
        self.assertIn("class ReadOnlyDatabase", text)
        self.assertIn("class ReadOnlyCollection", text)

    def test_script_registers_all_section_runners(self):
        from scripts.audit_production import SECTION_RUNNERS
        # 10 audit sections (Section 11 Atlas-manual is not a runner).
        self.assertEqual(len(SECTION_RUNNERS), 10)

    def test_script_has_main_entry(self):
        text = SCRIPT_PATH.read_text(encoding="utf-8")
        self.assertIn("def _main_entry", text)

    def test_script_has_canary_exception(self):
        text = SCRIPT_PATH.read_text(encoding="utf-8")
        self.assertIn("class CanaryFailed", text)


# ── Banned-methods set sanity ─────────────────────────────────────


class TestBannedMethodsSet(unittest.TestCase):
    """The _BANNED_COLLECTION_METHODS frozenset is the central
    enforcement point — its membership IS the security boundary."""

    EXPECTED = frozenset({
        "insert_one", "insert_many",
        "update_one", "update_many", "replace_one",
        "delete_one", "delete_many",
        "find_one_and_update", "find_one_and_replace", "find_one_and_delete",
        "bulk_write",
        "create_index", "create_indexes",
        "drop_index", "drop_indexes",
        "rename", "drop",
    })

    def test_membership_is_locked(self):
        from scripts.audit_production import _BANNED_COLLECTION_METHODS
        self.assertEqual(_BANNED_COLLECTION_METHODS, self.EXPECTED)


if __name__ == "__main__":
    unittest.main()
